"""
pytest configuration for the hl-allocator test suite.

Belt-and-suspenders sys.path insert: ensures ``import automation.*`` resolves
regardless of the CWD pytest is invoked from, even when the package is not
installed in editable mode.

NOTE: this file is generated by the export script from the monorepo template
``Python/tools/hl_allocator_export/templates/tests_conftest.py`` and copied
over ``automation/tests/conftest.py``.  ``parents[2]`` resolves to the parent
of the ``automation`` package — the repo root in this exported layout
(``Python/`` in the monorepo).  A dedicated template (rather than shipping the
monorepo conftest verbatim) keeps the exported file self-describing and
decoupled from monorepo-specific comments.
"""

import sys
from collections.abc import Iterator
from pathlib import Path

import pytest

# Absolute path to the repo root (parent of the ``automation`` package).
_REPO_ROOT = Path(__file__).resolve().parents[2]  # .../hl-allocator/

if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))


@pytest.fixture(autouse=True)
def _reset_structlog_state() -> Iterator[None]:
    """Reset global structlog + redaction state around every test.

    ``install_global_redaction()`` mutates *global* structlog configuration and
    flips a module-level ``_REDACTION_INSTALLED`` guard.  Some tests further
    reconfigure structlog (e.g. to point a PrintLogger at a StringIO buffer).
    Without this fixture, that mutated state leaks across tests and the suite
    becomes order-dependent.

    By resetting structlog defaults AND clearing the install guard before and
    after each test, every test starts from a clean, deterministic baseline.
    """
    import structlog

    import automation.core.redaction as _redaction

    def _reset() -> None:
        structlog.reset_defaults()
        _redaction._REDACTION_INSTALLED = False

    _reset()
    try:
        yield
    finally:
        _reset()
